### PR TITLE
Isaac/pipeline

### LINKED ISSUE #88: Folder Restructure
We need to create new folders to fit our redesign of the project. Start adding the new files into these folders.

Folders within modules,
- SupplyCloset
- DataSupplier
- ModelCoach
- Gym

### PR DESCRIPTION
**Pull request by ASAAR**
Adding the new file structure for the project. Closes #88 

@ZakeryFyke your singleton class should go in the utility_closet folder

### CODE REVIEW

**Comment by ASAAR** [comment]
@asclines what do you mean? the coach folder won't contain the models and I thought we said we'd wait to make folders for model types until we have more

**Comment by asclines** [comment]
@ASAAR i was under the impression that it would. This impression comes from that fact that I also thought the coach would be a singleton file. Is the coach going to be comprised of multiple files?

**Comment by ASAAR** [comment]
@asclines I see, that makes sense. I was thinking there might be classes which handle other things. But having the models in there makes sense long-term. I'll change it. Thank you!

**Comment by asclines** [comment]
@ASAAR one way we could look at it is model is the over-arching folder with a singleton inside of it for the coach, a folder for the modules, then maybe other folds for various utils or other model manipulating code

**Comment by ASAAR** [comment]
@asclines Yeah, I agree with that. It allows us to keep everything directly relating to models in the same place.

**Pull request merged**
