### PR TITLE
The Flood

### LINKED ISSUE #158: Remove old logger
Now that we have the MLTA module, we no longer need the old git logger written in bash.

### LINKED ISSUE #159: Remove toolbox
Because we don't like Ryan's code (or mine).

Reasons,
- The framework doesn't use any of that code anymore.
- We are phasing out R as a language, there's too many issues to deal with at this time.

### LINKED ISSUE #160: Relocate component analyzers
Reasons:

- Analyzers are not being utilized for reduction, and thus do not belong in the reducers directory.
- Analyzers may be used for something in the future, and thus do not yet require removal.

### LINKED ISSUE #162: Remove R code
Essentially all the code written in R is no longer in use, nor expected to be.

### PR DESCRIPTION
**Pull request by asclines**
# The Flood
**This Pull-Request is to be nothing but removals.**
In the Pull-Request we will have removals of all code contributors deem unworthy of moving forward to the next stage of this project. 
## If you disagree with a removal committed here:
Speak now or forever hold your peace.

## If you believe more should be removed
Checkout this branch `TheFlood` and commit those removals.

## Issues:
Commit 45f95833087c1918cf3091364b30de26818860e5 closes #158   
Commit 007449f80e4d995f39ea41d0f7548b694fd8dc19 closes #159  
Commit eac8cee4414bbb276be7cd7e15bfc4bbf9bccdd8 closes #160  
Commit 3a58b0980df5aec01d0d31d6570b847de622d6e8 closes #162

### CODE REVIEW

**Comment by asclines** [comment]
So @RyanMcBerg, with the R code gone, are there now unused datasets?

**Comment by ghost** [comment]
@asclines I believe they're all be used still. There were no R specific ones.

**Comment by asclines** [comment]
@RyanMcBerg Alright then.
@CodeSpaceHQ/clubmengel It's time, approve this PR if you are done with your deletions and approve everyone else's deletions. This PR gets merged once everyone approves.

**Review by ZakeryFyke — APPROVED** [review]

**Review by isaac-gs — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Let it Flood

**Pull request merged**
